import type { Config } from "tailwindcss";

const v = (name: string) => `rgb(var(--${name}) / <alpha-value>)`;
const SHADES = ["50", "100", "200", "300", "400", "500", "600", "700", "800", "900", "950"];
const FAMILIES = ["zinc", "slate", "gray", "emerald", "green", "rose", "red", "amber", "yellow", "orange", "sky", "blue", "teal", "cyan", "indigo", "purple", "violet", "fuchsia", "pink", "lime"];
const scale = (name: string, shades: string[]) => Object.fromEntries(shades.map((s) => [s, v(`${name}-${s}`)]));

const config: Config = {
  // `dark:` = any night appearance chosen in Personalise (or System on a dark device)
  darkMode: ["variant", [
    'html[data-scheme="dim"] &', 'html[data-scheme="dark"] &', 'html[data-scheme="midnight"] &',
    '@media (prefers-color-scheme: dark) { html[data-scheme="system"] & }',
  ]],
  content: ["./app/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}", "./lib/**/*.{ts,tsx}"],
  theme: {
    extend: {
      fontFamily: {
        sans: ["var(--font-geist-sans)", "ui-sans-serif", "system-ui", "sans-serif"],
        mono: ["var(--font-geist-mono)", "ui-monospace", "monospace"],
      },
      colors: {
        // Every colour is a CSS variable (see app/theme.css, generated by scripts/gen-theme.mjs) so
        // appearance, accent and contrast can change without rebuilding — and nothing flashes on load.
        canvas: v("canvas"),
        surface: v("surface"),
        ink: { DEFAULT: v("ink"), muted: v("ink-muted"), faint: v("ink-faint") },
        line: { DEFAULT: v("line"), strong: v("line-strong") },
        brand: scale("brand", ["50", "100", "200", "300", "400", "500", "600", "700", "800", "900"]),
        "on-brand": v("on-brand"),
        danger: { DEFAULT: v("danger"), strong: v("danger-strong") },
        ...Object.fromEntries(FAMILIES.map((f) => [f, scale(f, SHADES)])),
      },
      boxShadow: {
        card: "0 1px 2px rgb(var(--shadow) / 0.05), 0 1px 1px rgb(var(--shadow) / 0.03)",
        pop: "0 12px 32px -8px rgb(var(--shadow) / 0.22), 0 2px 6px rgb(var(--shadow) / 0.08)",
      },
      borderRadius: {
        xl: "14px",
      },
    },
  },
  plugins: [],
};

export default config;
