"""
Generates supabase/seed/seed.sql — realistic demo data for EventureOS.

All dates are relative to "today in Australia/Sydney" at the moment the SQL
runs, so the dashboard always looks live right after seeding. Re-running the
seed wipes and recreates the two demo organisations and demo users only.

Usage:  python3 supabase/seed/generate_seed.py
"""
import json
import uuid
from decimal import Decimal, ROUND_HALF_UP
from pathlib import Path

NS = uuid.UUID("7f1c1a52-6d0e-4d1e-9a51-2f0c0e0e5e01")
PASSWORD = "EventureDemo!2026"


class UID(str):
    """A deterministic uuid5; emitted in SQL as demo.u('key') to keep the file small."""
    key: str


def uid(key: str) -> "UID":
    u = UID(str(uuid.uuid5(NS, key)))
    u.key = key
    return u


def q(v):
    """SQL literal."""
    if v is None:
        return "null"
    if isinstance(v, UID):
        return f"demo.u('{v.key}')"
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, Decimal):
        return str(v)
    if isinstance(v, (int, float)):
        return repr(v)
    if isinstance(v, Raw):
        return v.sql
    if isinstance(v, (list, tuple)):
        return "array[" + ",".join(q(x) for x in v) + "]::text[]" if v else "'{}'::text[]"
    if isinstance(v, dict):
        return q(json.dumps(v)) + "::jsonb"
    return "'" + str(v).replace("'", "''") + "'"


class Raw:
    def __init__(self, sql):
        self.sql = sql


TODAY = "(now() at time zone 'Australia/Sydney')::date"


# Helpers live in the private `demo` schema (migration 0004_demo_helpers)
def D(days: int) -> Raw:
    """A date relative to today (Sydney)."""
    return Raw(f"demo.d({days})")


def AT(days: int, hhmm: str) -> Raw:
    """A timestamptz on a Sydney-local day/time."""
    return Raw(f"demo.at({days},'{hhmm}')")


def AGO(minutes) -> Raw:
    return Raw(f"demo.ago({int(minutes)})")


def AHEAD(minutes) -> Raw:
    return Raw(f"demo.ago({-int(minutes)})")


def money(x) -> Decimal:
    return Decimal(str(x)).quantize(Decimal("0.01"), rounding=ROUND_HALF_UP)


H = 60
DAY = 24 * 60

out: list[str] = []


def insert(table: str, rows: list[dict]):
    if not rows:
        return
    cols = list(rows[0].keys())
    for r in rows:
        assert list(r.keys()) == cols, f"{table}: column mismatch {r.keys()} vs {cols}"
    values = ",\n  ".join("(" + ", ".join(q(r[c]) for c in cols) + ")" for r in rows)
    out.append(f"insert into public.{table} ({', '.join(cols)}) values\n  {values};\n")


# ---------------------------------------------------------------------------
# Users
# ---------------------------------------------------------------------------
USERS = {
    "sarah": ("sarah@beanculture.demo", "Sarah Mitchell"),
    "jess": ("jess@beanculture.demo", "Jess Harper"),
    "tom": ("tom@beanculture.demo", "Tom Nguyen"),
    "liam": ("liam@copperandtonic.demo", "Liam O'Brien"),
    "admin": ("admin@eventureos.demo", "EventureOS Admin"),
}
U = {k: uid("user:" + k) for k in USERS}

out.append("-- EventureOS demo seed (generated by generate_seed.py — do not edit by hand)\n")
out.append("begin;\n")
out.append("delete from public.organisations where slug in ('bean-culture','copper-and-tonic');\n")
out.append(
    "delete from auth.users where email in ("
    + ", ".join(q(e) for e, _ in USERS.values())
    + ");\n"
)

for key, (email, name) in USERS.items():
    i = U[key]
    out.append(
        f"""insert into auth.users (instance_id, id, aud, role, email, encrypted_password, email_confirmed_at,
  raw_app_meta_data, raw_user_meta_data, created_at, updated_at, confirmation_token, recovery_token,
  email_change_token_new, email_change, email_change_token_current, reauthentication_token)
values ('00000000-0000-0000-0000-000000000000', {q(i)}, 'authenticated', 'authenticated', {q(email)},
  extensions.crypt({q(PASSWORD)}, extensions.gen_salt('bf')), now(),
  '{{"provider":"email","providers":["email"]}}'::jsonb, {q({"full_name": name})}, now() - interval '200 days', now(),
  '', '', '', '', '', '');
insert into auth.identities (id, user_id, provider_id, identity_data, provider, last_sign_in_at, created_at, updated_at)
values (gen_random_uuid(), {q(i)}, {q(i)}, {q({"sub": i, "email": email, "email_verified": True})}, 'email', now(), now(), now());
"""
    )
out.append(f"insert into public.platform_admins (user_id) values ({q(U['admin'])});\n")

# ---------------------------------------------------------------------------
# Organisations
# ---------------------------------------------------------------------------
BC = uid("org:bean-culture")
CT = uid("org:copper-and-tonic")

insert("organisations", [
    dict(id=BC, name="Bean Culture", slug="bean-culture",
         business_type="Mobile coffee & event catering", brand_colour="#6D4AFF",
         contact_email="info@beanculture.com.au", contact_phone=None, address="Canberra, ACT",
         website=None, plan="growth", created_by=U["sarah"]),
    dict(id=CT, name="Copper & Tonic Mobile Bar", slug="copper-and-tonic",
         business_type="Mobile cocktail bar", brand_colour="#B4632B",
         contact_email="hello@copperandtonic.demo", contact_phone=None, address="Queanbeyan, NSW",
         website=None, plan="starter", created_by=U["liam"]),
])

insert("organisation_users", [
    dict(organisation_id=BC, user_id=U["sarah"], role=Raw("'owner'"), title="Owner"),
    dict(organisation_id=BC, user_id=U["jess"], role=Raw("'manager'"), title="Events Manager"),
    dict(organisation_id=BC, user_id=U["tom"], role=Raw("'staff'"), title="Lead Barista"),
    dict(organisation_id=CT, user_id=U["liam"], role=Raw("'owner'"), title="Owner"),
    dict(organisation_id=CT, user_id=U["sarah"], role=Raw("'admin'"), title="Partner"),
])

# ---------------------------------------------------------------------------
# Per-organisation builder
# ---------------------------------------------------------------------------


class Org:
    def __init__(self, org_id, key):
        self.id = org_id
        self.key = key
        self.customers, self.contacts, self.enquiries, self.events = [], [], [], []
        self.quotes, self.sections, self.items, self.versions = [], [], [], []
        self.invoices, self.payments, self.threads, self.messages = [], [], [], []
        self.tasks, self.activity, self.notifications, self.cal_events = [], [], [], []
        self.documents, self.event_contacts = [], []
        self.enq_n = 1000
        self.ev_n = 2000
        self.q_n = 1000
        self.inv_n = 1000

    def k(self, *parts):
        return uid(self.key + ":" + ":".join(parts))

    def log(self, when, action, entity_type, entity_id, summary, actor=None, actor_type="user",
            actor_label=None, event_id=None, customer_id=None, enquiry_id=None, changes=None, metadata=None):
        self.activity.append(dict(
            organisation_id=self.id, actor_id=actor, actor_type=actor_type, actor_label=actor_label,
            action=action, entity_type=entity_type, entity_id=entity_id, customer_id=customer_id,
            event_id=event_id, enquiry_id=enquiry_id, summary=summary, changes=changes, metadata=metadata,
            created_at=when))


def line_total(ln) -> Decimal:
    return money(Decimal(str(ln["qty"])) * Decimal(str(ln["price"])) * (1 - Decimal(str(ln.get("disc", 0))) / 100))


def quote_totals(lines):
    sub = sum((line_total(ln) for ln in lines if not ln.get("optional")), Decimal("0"))
    sub = money(sub)
    tax = money(sub * Decimal("0.1"))
    return sub, tax, money(sub + tax)


def build_quote(o: Org, key, event, customer, title, sections, *, status, versions,
                issue_days, expiry_days, notes=None, terms=None, unpublished=False):
    """sections: list of (title, [line dicts]); versions: list of (status, published_minutes_ago, extra)"""
    o.q_n += 1
    qid = o.k("quote", key)
    all_lines = [ln for _, lines in sections for ln in lines]
    sub, tax, total = quote_totals(all_lines)
    for si, (stitle, lines) in enumerate(sections):
        sid = o.k("qsec", key, str(si))
        o.sections.append(dict(id=sid, organisation_id=o.id, quote_id=qid, title=stitle,
                               description=None, position=si, is_optional=False))
        for li, ln in enumerate(lines):
            o.items.append(dict(organisation_id=o.id, quote_id=qid, section_id=sid, name=ln["name"],
                                description=ln.get("desc"), quantity=ln["qty"], unit=ln.get("unit"),
                                unit_price=ln["price"], tax_rate=10, discount_percent=ln.get("disc", 0),
                                is_optional=bool(ln.get("optional")), is_package=bool(ln.get("package")),
                                position=li))

    current = None
    for vi, (vstatus, mins_ago, extra) in enumerate(versions, start=1):
        vid = o.k("qver", key, str(vi))
        current = vid
        # earlier versions carry a slightly different total to show history
        v_sub, v_tax, v_total = (sub, tax, total)
        v_snap = Raw(f"demo.quote_snapshot('{qid}')")
        if vi < len(versions):
            v_sub = money(sub * Decimal("0.9"))
            v_tax = money(v_sub * Decimal("0.1"))
            v_total = money(v_sub + v_tax)
            v_snap = Raw(f"demo.quote_snapshot('{qid}', 0.9)")
        o.versions.append(dict(
            id=vid, organisation_id=o.id, quote_id=qid, version_number=vi, snapshot=v_snap,
            subtotal=v_sub, tax_total=v_tax, total=v_total, status=Raw(f"'{vstatus}'"),
            published_at=AGO(mins_ago), published_by=extra.get("by"),
            viewed_at=AGO(extra["viewed"]) if extra.get("viewed") else None,
            responded_at=AGO(extra["responded"]) if extra.get("responded") else None,
            accepted_by_name=extra.get("accepted_by"),
            acceptance_ip=Raw("'203.0.113.24'::inet") if extra.get("accepted_by") else None,
            acceptance_user_agent="Mozilla/5.0 (iPhone; CPU iPhone OS 18_5 like Mac OS X)" if extra.get("accepted_by") else None,
            decline_reason=None))
    o.quotes.append(dict(
        id=qid, organisation_id=o.id, number=o.q_n, event_id=event["id"], customer_id=customer["id"],
        title=title, status=Raw(f"'{status}'"), issue_date=D(issue_days), expiry_date=D(expiry_days),
        notes=notes, terms=terms, current_version_id=None, has_unpublished_changes=unpublished,
        created_by=event["assigned_to"], _current=current))
    return dict(id=qid, number=o.q_n, sub=sub, tax=tax, total=total)


def add_invoice(o: Org, key, customer, event, quote, kind, amount_total, issue_days, due_days, status,
                paid=0.0, paid_minutes_ago=None, method="Bank transfer"):
    o.inv_n += 1
    iid = o.k("inv", key)
    total = money(amount_total)
    sub = money(total / Decimal("1.1"))
    tax = money(total - sub)
    o.invoices.append(dict(
        id=iid, organisation_id=o.id, number=f"INV-{o.inv_n}", customer_id=customer["id"],
        event_id=event["id"] if event else None, quote_id=quote["id"] if quote else None, kind=kind,
        issue_date=D(issue_days), due_date=D(due_days), subtotal=sub, tax_total=tax, total=total,
        amount_paid=money(paid), status=Raw(f"'{status}'")))
    if paid > 0:
        o.payments.append(dict(organisation_id=o.id, invoice_id=iid, amount=money(paid),
                               paid_at=AGO(paid_minutes_ago), method=method,
                               reference=f"INV-{o.inv_n}"))
    return dict(id=iid, number=f"INV-{o.inv_n}", total=total)


def thread(o: Org, key, subject, classification, state, messages, *, customer=None, event=None,
           enquiry=None, confidence=0.95, classified_by="rules"):
    tid = o.k("thread", key)
    parts = sorted({m["from_email"] for m in messages} | {e for m in messages for e in m["to"]})
    last = min(m["ago"] for m in messages)
    inbound = [m["ago"] for m in messages if m["dir"] == "inbound"]
    o.threads.append(dict(
        id=tid, organisation_id=o.id, gmail_thread_id=f"demo-{key}", subject=subject,
        customer_id=customer["id"] if customer else None, event_id=event["id"] if event else None,
        enquiry_id=enquiry["id"] if enquiry else None, classification=Raw(f"'{classification}'"),
        classification_confidence=confidence, classified_by=classified_by, state=state,
        participants=parts, message_count=len(messages), last_message_at=AGO(last),
        last_inbound_at=AGO(min(inbound)) if inbound else None))
    for mi, m in enumerate(messages):
        o.messages.append(dict(
            organisation_id=o.id, thread_id=tid, gmail_message_id=f"demo-{key}-{mi}",
            direction=m["dir"], from_email=m["from_email"], from_name=m["from_name"], to_emails=m["to"],
            subject=subject if mi == 0 else "Re: " + subject, snippet=m["body"][:140].replace("\n", " "),
            body_text=m["body"], sent_at=AGO(m["ago"]), is_read=m.get("read", True),
            sent_by=m.get("by")))
    return tid


def msg(direction, from_email, from_name, to, ago, body, by=None, read=True):
    return dict(dir=direction, from_email=from_email, from_name=from_name, to=to, ago=ago, body=body,
                by=by, read=read)


# ===========================================================================
# BEAN CULTURE
# ===========================================================================
bc = Org(BC, "bc")
BC_EMAIL = "info@beanculture.com.au"
S, J, T = U["sarah"], U["jess"], U["tom"]

cal = {
    "main": bc.k("cal", "main"), "cart1": bc.k("cal", "cart1"),
    "cart2": bc.k("cal", "cart2"), "catering": bc.k("cal", "catering"),
}
insert("calendar_connections", [
    dict(id=cal["main"], organisation_id=BC, name="Main Events", colour="#6D4AFF", is_default=True),
    dict(id=cal["cart1"], organisation_id=BC, name="Coffee Cart 1", colour="#0E9F6E", is_default=False),
    dict(id=cal["cart2"], organisation_id=BC, name="Coffee Cart 2", colour="#0284C7", is_default=False),
    dict(id=cal["catering"], organisation_id=BC, name="Catering", colour="#D97706", is_default=False),
])


def customer(o: Org, key, name, *, kind="individual", company=None, email=None, phone=None, address=None,
             since=-200, source="website", contact=None, notes=None, tags=()):
    cid = o.k("cust", key)
    row = dict(id=cid, organisation_id=o.id, kind=kind, name=name, company=company, email=email, phone=phone,
               address=address, notes=notes, source=Raw(f"'{source}'"), tags=list(tags), customer_since=D(since))
    o.customers.append(row)
    first, last = (contact or name).split(" ", 1) if " " in (contact or name) else ((contact or name), None)
    ctid = o.k("contact", key)
    o.contacts.append(dict(id=ctid, organisation_id=o.id, customer_id=cid, first_name=first, last_name=last,
                           email=email, phone=phone, position=None if kind == "individual" else "Organiser",
                           is_primary=True))
    return dict(id=cid, contact_id=ctid, name=name, email=email, contact=contact or name)


def event(o: Org, key, name, cust, *, etype, days, start, finish, venue, address, guests, budget, status,
          assigned, staff=(), services=(), equipment=(), requirements=None, internal=None, cnotes=None,
          next_action=None, next_due=None, calendar=None, enquiry=None):
    o.ev_n += 1
    eid = o.k("event", key)
    row = dict(id=eid, organisation_id=o.id, number=o.ev_n, name=name, customer_id=cust["id"],
               primary_contact_id=cust["contact_id"], enquiry_id=None, event_type=etype, event_date=D(days),
               start_time=start, finish_time=finish, venue=venue, address=address, guest_count=guests,
               budget=budget, status=Raw(f"'{status}'"), assigned_to=assigned, assigned_staff=Raw(
                   "array[" + ",".join(q(s) + "::uuid" for s in staff) + "]::uuid[]" if staff else "'{}'::uuid[]"),
               internal_notes=internal, customer_notes=cnotes, requirements=requirements,
               services=list(services), equipment=list(equipment), next_action=next_action,
               next_action_due=next_due, created_by=assigned, _enquiry=enquiry)
    o.events.append(row)
    o.event_contacts.append(dict(organisation_id=o.id, event_id=eid, contact_id=cust["contact_id"],
                                 role="Primary contact"))
    if calendar and status in ("confirmed", "completed"):
        o.cal_events.append(dict(
            organisation_id=o.id, calendar_connection_id=calendar, event_id=eid, title=name,
            starts_at=AT(days, start), ends_at=AT(days, finish), location=venue, kind="event",
            sync_status="local"))
    return dict(id=eid, number=o.ev_n, name=name, assigned_to=assigned, days=days, customer=cust)


def enquiry(o: Org, key, title, *, cust=None, contact_name=None, contact_email=None, contact_phone=None,
            company=None, etype, days, guests, budget, venue, message, source, status, assigned,
            received_ago, last_contact_ago=None, next_action=None, next_due=None, classification=None,
            confidence=None, lost_reason=None):
    o.enq_n += 1
    nid = o.k("enq", key)
    o.enquiries.append(dict(
        id=nid, organisation_id=o.id, number=o.enq_n, customer_id=cust["id"] if cust else None,
        contact_id=cust["contact_id"] if cust else None, event_id=None, title=title,
        contact_name=contact_name or (cust["contact"] if cust else None),
        contact_email=contact_email or (cust["email"] if cust else None), contact_phone=contact_phone,
        company=company, event_type=etype, event_date=D(days) if days is not None else None,
        guest_count=guests, budget=budget, venue=venue, message=message, source=Raw(f"'{source}'"),
        status=Raw(f"'{status}'"),
        classification=Raw(f"'{classification}'") if classification else None,
        classification_confidence=confidence, assigned_to=assigned, received_at=AGO(received_ago),
        last_contact_at=AGO(last_contact_ago) if last_contact_ago else None, next_action=next_action,
        next_action_due=next_due, lost_reason=lost_reason, created_by=assigned))
    return dict(id=nid, number=o.enq_n, received_ago=received_ago, title=title, customer=cust)


def link(o: Org, enq, ev):
    for r in o.enquiries:
        if r["id"] == enq["id"]:
            r["event_id"] = ev["id"]
    for r in o.events:
        if r["id"] == ev["id"]:
            r["enquiry_id"] = enq["id"]


# ---- pricing helpers (Bean Culture) ---------------------------------------
def cart_hire(hours=4):
    return {"name": "Espresso cart hire", "desc": f"Commercial espresso cart, grinder & setup — up to {hours} hours",
            "qty": 1, "unit": "event", "price": 450.0}


def barista(n, hours):
    return {"name": "Barista", "desc": f"{n} barista{'s' if n > 1 else ''} × {hours} hrs", "qty": n * hours,
            "unit": "hour", "price": 55.0}


def cups(n):
    return {"name": "Specialty coffee", "desc": "House blend espresso, all milk-based & black coffees",
            "qty": n, "unit": "cup", "price": 4.20}


def travel(amount=80.0):
    return {"name": "Travel & setup", "desc": "Canberra metro delivery, setup and pack-down",
            "qty": 1, "unit": "event", "price": amount}


# ---- customers -------------------------------------------------------------
c_smith = customer(bc, "smith", "Emma Smith", email="emma.smith@example.com", phone="0412 555 101",
                   address="Ngunnawal, ACT", since=-128, source="website", tags=("wedding",),
                   notes="Marrying James Taylor. Very organised — prefers email over calls.")
c_captech = customer(bc, "captech", "Capital Tech Partners", kind="company", company="Capital Tech Partners",
                     contact="Daniel Reeves", email="daniel.reeves@example.com", phone="02 6100 5520",
                     address="Level 4, 12 Moore St, Canberra City ACT", since=-410, source="referral",
                     tags=("corporate", "repeat"), notes="Repeat corporate client. PO number required on invoices.")
c_harper = customer(bc, "harper", "Harper & Lane Architects", kind="company", company="Harper & Lane Architects",
                    contact="Olivia Lane", email="olivia@example.net", phone="02 6100 7788",
                    address="Braddon, ACT", since=-60, source="instagram", tags=("corporate",))
c_school = customer(bc, "school", "Northside Primary P&C", kind="company", company="Northside Primary P&C",
                    contact="Rebecca Walsh", email="rebecca.walsh@example.org", phone="0433 555 212",
                    since=-300, source="referral", tags=("community", "repeat"))
c_molonglo = customer(bc, "molonglo", "Molonglo Property Group", kind="company",
                      company="Molonglo Property Group", contact="Marcus Chen",
                      email="marcus.chen@example.com", phone="0421 555 330", since=-20, source="email",
                      tags=("corporate",))
c_sharma = customer(bc, "sharma", "Priya Sharma", email="priya.sharma@example.com", phone="0450 555 481",
                    since=-15, source="website", tags=("birthday",))
c_runclub = customer(bc, "runclub", "Brindabella Running Club", kind="company",
                     company="Brindabella Running Club", contact="Kate Ellis", email="kate.ellis@example.org",
                     phone="0402 555 199", since=-380, source="facebook", tags=("community", "repeat"))
c_wellness = customer(bc, "wellness", "Lakeside Wellness Studio", kind="company",
                      company="Lakeside Wellness Studio", contact="Hannah Brooks",
                      email="hannah@example.net", phone="0419 555 640", since=-90, source="instagram")
c_summit = customer(bc, "summit", "Summit Financial Advisers", kind="company",
                    company="Summit Financial Advisers", contact="Andrew Kim",
                    email="andrew.kim@example.com", phone="02 6100 3344", since=-240, source="referral",
                    tags=("corporate", "repeat"))
c_bennett = customer(bc, "bennett", "Grace Bennett", email="grace.bennett@example.com", phone="0477 555 902",
                     since=-10, source="referral", tags=("wedding",), notes="Referred by Emma Smith.")
c_makers = customer(bc, "makers", "Canberra Makers Market", kind="company", company="Canberra Makers Market",
                    contact="Sophie Turner", email="sophie@example.org", phone="0400 555 713", since=-150,
                    source="email", tags=("markets",))
c_kingston = customer(bc, "kingston", "Kingston Foreshore Pop-up", kind="company",
                      company="Foreshore Events Collective", contact="Ben Carter", email="ben.carter@example.com",
                      since=-45, source="phone")
c_rotary = customer(bc, "rotary", "Kingston Rotary Club", kind="company", company="Kingston Rotary Club",
                    contact="Peter Hughes", email="peter.hughes@example.org", phone="0411 555 870", since=-4,
                    source="referral")
c_harbour = customer(bc, "harbour", "Redgum Films", kind="company", company="Redgum Films",
                     contact="Chloe Martin", email="chloe@example.net", phone="0434 555 118", since=-3,
                     source="phone")
c_parkes = customer(bc, "parkes", "Parkes Conference Co", kind="company", company="Parkes Conference Co",
                    contact="Rachel Adams", email="rachel.adams@example.com", phone="02 6100 9001", since=-1,
                    source="email")
c_lucy = customer(bc, "lucy", "Lucy Martin", email="lucy.martin@example.com", since=-35, source="website")

# ---- events + enquiries + quotes + invoices --------------------------------
# 1. Smith wedding — confirmed, +23 days, quote v2 accepted, deposit paid, final due
e = enquiry(bc, "smith", "Coffee cart for our wedding", cust=c_smith, etype="Wedding", days=23, guests=100,
            budget=3500, venue="Lanyon Homestead", source="website", status="won", assigned=J,
            received_ago=120 * DAY, last_contact_ago=1 * DAY,
            message="Hi! We're getting married and would love a coffee cart for the post-ceremony drinks and "
                    "reception. Around 80–100 guests. Do you do oat milk and chai?",
            classification="event_enquiry", confidence=0.97)
ev_smith = event(bc, "smith", "Smith & Taylor Wedding", c_smith, etype="Wedding", days=23, start="14:30",
                 finish="19:30", venue="Lanyon Homestead", address="Tharwa Dr, Tharwa ACT", guests=100,
                 budget=3500, status="confirmed", assigned=J, staff=(J, T),
                 services=("Espresso cart", "Hot chocolate & chai", "Plant milks"),
                 equipment=("Cart 1", "La Marzocco Linea", "Mazzer grinder", "Festoon lighting"),
                 requirements="Cart set up on the lawn beside the marquee. Power available (15A). "
                              "Oat & almond milk. Signage: 'Emma & James'.",
                 internal="Guest count increased from 80 to 100 after RSVPs. Confirm final numbers 14 days out.",
                 cnotes="Please wear black. Bridal party coffees first after photos.",
                 next_action="Send final details form", next_due=AT(2, "09:00"), calendar=cal["cart1"])
link(bc, e, ev_smith)
lines_smith = [("Coffee service", [cart_hire(5), barista(2, 5), cups(220),
                                  {"name": "Hot chocolate & chai", "desc": "Chai latte & hot chocolate options",
                                   "qty": 40, "unit": "cup", "price": 4.0},
                                  {"name": "Plant-based milks", "desc": "Oat & almond", "qty": 1,
                                   "unit": "event", "price": 60.0}]),
               ("Extras", [travel(120.0),
                           {"name": "Custom cup stickers", "desc": "'Emma & James' printed stickers",
                            "qty": 250, "unit": "each", "price": 0.45, "optional": True}])]
q_smith = build_quote(bc, "smith", ev_smith, c_smith, "Wedding coffee cart — Smith & Taylor", lines_smith,
                      status="accepted", issue_days=-95, expiry_days=-65,
                      notes="Includes two baristas for five hours of service.",
                      terms="30% deposit secures the date. Balance due 14 days before the event.",
                      versions=[("superseded", 100 * DAY, {"by": J, "viewed": 99 * DAY}),
                                ("accepted", 94 * DAY, {"by": J, "viewed": 93 * DAY, "responded": 92 * DAY,
                                                        "accepted_by": "Emma Smith"})])
inv_smith_dep = add_invoice(bc, "smith-dep", c_smith, ev_smith, q_smith, "deposit", q_smith["total"] * Decimal("0.3"),
                            -92, -85, "paid", paid=q_smith["total"] * Decimal("0.3"), paid_minutes_ago=88 * DAY)
inv_smith_fin = add_invoice(bc, "smith-fin", c_smith, ev_smith, q_smith, "final",
                            q_smith["total"] - inv_smith_dep["total"],
                            -2, 9, "awaiting_payment")

# 2. Capital Tech offsite — completed -40 days, paid
e = enquiry(bc, "captech-offsite", "Coffee cart for quarterly offsite", cust=c_captech, etype="Corporate",
            days=-40, guests=60, budget=1500, venue="Capital Tech Partners office", source="referral",
            status="won", assigned=S, received_ago=70 * DAY, last_contact_ago=38 * DAY,
            message="We're running our quarterly offsite and want a barista cart for the morning session.")
ev_offsite = event(bc, "captech-offsite", "Capital Tech Quarterly Offsite", c_captech, etype="Corporate",
                   days=-40, start="08:00", finish="12:00", venue="Capital Tech Partners",
                   address="12 Moore St, Canberra City ACT", guests=60, budget=1500, status="completed",
                   assigned=S, staff=(T,), services=("Espresso cart",), equipment=("Cart 2",),
                   calendar=cal["cart2"])
link(bc, e, ev_offsite)
q_off = build_quote(bc, "captech-offsite", ev_offsite, c_captech, "Morning coffee service — quarterly offsite",
                    [("Coffee service", [cart_hire(4), barista(1, 4), cups(120), travel()])],
                    status="accepted", issue_days=-66, expiry_days=-36,
                    versions=[("accepted", 66 * DAY, {"by": S, "viewed": 65 * DAY, "responded": 64 * DAY,
                                                      "accepted_by": "Daniel Reeves"})])
add_invoice(bc, "captech-offsite", c_captech, ev_offsite, q_off, "full", q_off["total"], -40, -26, "paid",
            paid=q_off["total"], paid_minutes_ago=30 * DAY)

# 3. Capital Tech end of year — planning +68 days, draft quote (unpublished)
e = enquiry(bc, "captech-eoy", "End of year party — coffee & dessert bar", cust=c_captech, etype="Corporate",
            days=68, guests=150, budget=4000, venue="National Arboretum Canberra", source="email",
            status="won", assigned=S, received_ago=9 * DAY, last_contact_ago=6 * DAY,
            message="Following the offsite, we'd love you back for our end of year party. Evening event, "
                    "espresso martinis-style mocktails and dessert coffees.",
            classification="event_enquiry", confidence=0.93)
ev_eoy = event(bc, "captech-eoy", "Capital Tech End of Year Party", c_captech, etype="Corporate", days=68,
               start="17:00", finish="22:00", venue="National Arboretum Canberra",
               address="Forest Dr, Molonglo Valley ACT", guests=150, budget=4000, status="planning",
               assigned=S, staff=(S, T), services=("Espresso cart", "Dessert coffees", "Catering"),
               requirements="Evening service, indoor venue. Client wants affogato station.",
               next_action="Finish and send quote", next_due=AT(1, "12:00"))
link(bc, e, ev_eoy)
build_quote(bc, "captech-eoy", ev_eoy, c_captech, "End of year coffee & dessert bar",
            [("Coffee service", [cart_hire(5), barista(2, 5), cups(300)]),
             ("Dessert bar", [{"name": "Affogato station", "desc": "Vanilla bean gelato & espresso",
                               "qty": 150, "unit": "serve", "price": 7.5, "package": True},
                              {"name": "Pastry & biscotti platter", "qty": 150, "unit": "guest", "price": 6.5}]),
             ("Extras", [travel(120.0)])],
            status="draft", issue_days=0, expiry_days=30, unpublished=True, versions=[])

# 4. Harper & Lane office opening — TODAY, confirmed
e = enquiry(bc, "harper", "Office opening morning tea", cust=c_harper, etype="Corporate", days=0, guests=45,
            budget=1200, venue="Harper & Lane studio", source="instagram", status="won", assigned=J,
            received_ago=35 * DAY, last_contact_ago=1 * DAY,
            message="Saw your cart on Instagram — we're opening our new studio and want coffee for guests.")
ev_harper = event(bc, "harper", "Harper & Lane Studio Opening", c_harper, etype="Corporate", days=0,
                  start="07:30", finish="10:30", venue="Harper & Lane Architects",
                  address="Lonsdale St, Braddon ACT", guests=45, budget=1200, status="confirmed", assigned=J,
                  staff=(T,), services=("Espresso cart",), equipment=("Cart 1",),
                  requirements="Loading zone access via rear lane from 6:45am.",
                  next_action="Event today — cart departs 6:30am", calendar=cal["cart1"])
link(bc, e, ev_harper)
q_harper = build_quote(bc, "harper", ev_harper, c_harper, "Studio opening coffee service",
                       [("Coffee service", [cart_hire(3), barista(1, 3), cups(90), travel()])],
                       status="accepted", issue_days=-30, expiry_days=0,
                       versions=[("accepted", 30 * DAY, {"by": J, "viewed": 29 * DAY, "responded": 28 * DAY,
                                                         "accepted_by": "Olivia Lane"})])
add_invoice(bc, "harper", c_harper, ev_harper, q_harper, "full", q_harper["total"], -3, 7, "awaiting_payment")

# 5. Summit board meeting — tomorrow, confirmed
ev_board = event(bc, "summit-board", "Summit Financial Board Meeting", c_summit, etype="Corporate", days=1,
                 start="08:30", finish="11:30", venue="Summit Financial Advisers",
                 address="Barton, ACT", guests=20, budget=700, status="confirmed", assigned=S, staff=(T,),
                 services=("Espresso cart",), equipment=("Cart 2",), calendar=cal["cart2"])
q_board = build_quote(bc, "summit-board", ev_board, c_summit, "Board meeting coffee service",
                      [("Coffee service", [cart_hire(3), barista(1, 3), cups(40)])],
                      status="accepted", issue_days=-12, expiry_days=18,
                      versions=[("accepted", 12 * DAY, {"by": S, "viewed": 12 * DAY - 90, "responded": 11 * DAY,
                                                        "accepted_by": "Andrew Kim"})])
add_invoice(bc, "summit-board", c_summit, ev_board, q_board, "full", q_board["total"], -10, 14, "awaiting_payment")

# 6. Fun run — +3 days, confirmed, paid
e = enquiry(bc, "runclub", "Winter fun run — coffee at the finish line", cust=c_runclub, etype="Community",
            days=3, guests=250, budget=1800, venue="Stromlo Forest Park", source="facebook", status="won",
            assigned=J, received_ago=40 * DAY, last_contact_ago=2 * DAY,
            message="Back again for the winter fun run! Same as last year please — 250 runners.")
ev_run = event(bc, "runclub", "Brindabella Winter Fun Run", c_runclub, etype="Community", days=3,
               start="06:30", finish="11:00", venue="Stromlo Forest Park", address="Uriarra Rd, Stromlo ACT",
               guests=250, budget=1800, status="confirmed", assigned=J, staff=(J, T),
               services=("Espresso cart", "Hot chocolate"), equipment=("Cart 2", "Generator", "Gazebo"),
               requirements="No mains power — bring generator. Park beside the finish chute.",
               next_action="Confirm generator fuel & parking", next_due=AT(1, "16:00"), calendar=cal["cart2"])
link(bc, e, ev_run)
q_run = build_quote(bc, "runclub", ev_run, c_runclub, "Fun run finish-line coffee",
                    [("Coffee service", [cart_hire(4), barista(2, 4.5), cups(260),
                                         {"name": "Hot chocolate", "qty": 60, "unit": "cup", "price": 4.0},
                                         {"name": "Generator hire", "qty": 1, "unit": "event", "price": 90.0}]),
                     ("Discount", [{"name": "Community club discount", "desc": "Returning community client",
                                    "qty": 1, "unit": "event", "price": -120.0}])],
                    status="accepted", issue_days=-36, expiry_days=-6,
                    versions=[("accepted", 36 * DAY, {"by": J, "viewed": 35 * DAY, "responded": 35 * DAY - 200,
                                                      "accepted_by": "Kate Ellis"})])
add_invoice(bc, "runclub", c_runclub, ev_run, q_run, "full", q_run["total"], -30, -16, "paid",
            paid=q_run["total"], paid_minutes_ago=18 * DAY)

# 7. School fete — +5 days, confirmed, deposit paid
e = enquiry(bc, "school", "Spring fete coffee cart", cust=c_school, etype="Community", days=5, guests=400,
            budget=2000, venue="Northside Primary School", source="referral", status="won", assigned=T,
            received_ago=50 * DAY, last_contact_ago=4 * DAY,
            message="Our P&C would love the coffee cart back at the spring fete.")
ev_school = event(bc, "school", "Northside Primary Spring Fete", c_school, etype="Community", days=5,
                  start="09:00", finish="14:00", venue="Northside Primary School", address="Ngunnawal, ACT",
                  guests=400, budget=2000, status="confirmed", assigned=T, staff=(T,),
                  services=("Espresso cart",), equipment=("Cart 1",), calendar=cal["cart1"],
                  cnotes="Fundraiser — 10% of sales donated back to the P&C.")
link(bc, e, ev_school)
q_school = build_quote(bc, "school", ev_school, c_school, "Spring fete coffee cart",
                       [("Coffee service", [cart_hire(5), barista(2, 5), cups(300)])],
                       status="accepted", issue_days=-45, expiry_days=-15,
                       versions=[("accepted", 45 * DAY, {"by": T, "viewed": 44 * DAY, "responded": 42 * DAY,
                                                         "accepted_by": "Rebecca Walsh"})])
add_invoice(bc, "school-dep", c_school, ev_school, q_school, "deposit", q_school["total"] * Decimal("0.3"), -42, -35,
            "paid", paid=q_school["total"] * Decimal("0.3"), paid_minutes_ago=6 * DAY)

# 8. Cancelled pop-up
ev_kingston = event(bc, "kingston", "Kingston Foreshore Pop-up", c_kingston, etype="Market", days=9,
                    start="10:00", finish="15:00", venue="Kingston Foreshore", address="Kingston ACT", guests=300,
                    budget=900, status="cancelled", assigned=S,
                    internal="Organiser cancelled — council permit not approved in time.")

# 9. Property launch — +12 days, awaiting approval (quote viewed)
e_mol = enquiry(bc, "molonglo", "Barista service for display village launch", cust=c_molonglo,
                etype="Corporate", days=12, guests=200, budget=3000, venue="Whitlam display village",
                source="email", status="quote_sent", assigned=S, received_ago=11 * DAY,
                last_contact_ago=6 * 60, message="We're launching a new display village over a weekend and need "
                "a barista cart both days, 9am–3pm.", classification="event_enquiry", confidence=0.91,
                next_action="Reply to Marcus's questions", next_due=AHEAD(3 * H))
ev_mol = event(bc, "molonglo", "Molonglo Display Village Launch", c_molonglo, etype="Corporate", days=12,
               start="09:00", finish="15:00", venue="Whitlam display village", address="Whitlam, ACT",
               guests=200, budget=3000, status="awaiting_approval", assigned=S, staff=(S, T),
               services=("Espresso cart", "Branded cups"), equipment=("Cart 1",),
               next_action="Reply to Marcus's questions", next_due=AHEAD(3 * H))
link(bc, e_mol, ev_mol)
q_mol = build_quote(bc, "molonglo", ev_mol, c_molonglo, "Display village launch — 2 day barista service",
                    [("Saturday", [cart_hire(6), barista(2, 6), cups(200)]),
                     ("Sunday", [cart_hire(6), barista(2, 6), cups(180)]),
                     ("Extras", [travel(), {"name": "Branded cups", "desc": "Molonglo logo cups",
                                            "qty": 400, "unit": "each", "price": 0.45, "optional": True}])],
                    status="viewed", issue_days=-3, expiry_days=11,
                    versions=[("viewed", 3 * DAY, {"by": S, "viewed": 20 * H})])

# 10. Sharma 40th — +18 days, quoted, follow-up overdue
e_sh = enquiry(bc, "sharma", "40th birthday — coffee cart in the garden", cust=c_sharma, etype="Birthday",
               days=18, guests=60, budget=1200, venue="Private residence, Red Hill", source="website",
               status="quote_sent", assigned=J, received_ago=8 * DAY, last_contact_ago=4 * DAY,
               message="Hi, I'm planning my 40th at home (garden party, ~60 people). Could you do coffee from "
                       "2pm–5pm?", classification="event_enquiry", confidence=0.96,
               next_action="Follow up on quote", next_due=AT(-1, "10:00"))
ev_sh = event(bc, "sharma", "Priya's 40th Birthday", c_sharma, etype="Birthday", days=18, start="14:00",
              finish="17:00", venue="Private residence", address="Red Hill, ACT", guests=60, budget=1200,
              status="quoted", assigned=J, staff=(T,), services=("Espresso cart",),
              next_action="Follow up on quote", next_due=AT(-1, "10:00"))
link(bc, e_sh, ev_sh)
q_sh = build_quote(bc, "sharma", ev_sh, c_sharma, "Garden party coffee cart",
                   [("Coffee service", [cart_hire(3), barista(1, 3), cups(110), travel()])],
                   status="sent", issue_days=-4, expiry_days=10,
                   versions=[("sent", 4 * DAY, {"by": J})])

# 11. Wellness retreat — completed -12, invoice overdue
e = enquiry(bc, "wellness", "Morning coffee for wellness retreat", cust=c_wellness, etype="Corporate",
            days=-12, guests=40, budget=1100, venue="Lakeside Wellness Studio", source="instagram", status="won",
            assigned=T, received_ago=45 * DAY, last_contact_ago=1 * DAY,
            message="Running a Saturday retreat — could we get coffee & matcha for 40 people?")
ev_well = event(bc, "wellness", "Lakeside Wellness Retreat", c_wellness, etype="Corporate", days=-12,
                start="07:00", finish="11:00", venue="Lakeside Wellness Studio", address="Kingston, ACT",
                guests=40, budget=1100, status="completed", assigned=T, staff=(T,),
                services=("Espresso cart", "Matcha"), equipment=("Cart 2",), calendar=cal["cart2"],
                next_action="Chase overdue invoice", next_due=AT(0, "11:00"))
link(bc, e, ev_well)
q_well = build_quote(bc, "wellness", ev_well, c_wellness, "Retreat coffee & matcha",
                     [("Coffee service", [cart_hire(4), barista(1, 4), cups(80),
                                          {"name": "Matcha lattes", "qty": 30, "unit": "cup", "price": 5.0},
                                          travel()])],
                     status="accepted", issue_days=-40, expiry_days=-10,
                     versions=[("accepted", 40 * DAY, {"by": T, "viewed": 39 * DAY, "responded": 38 * DAY,
                                                       "accepted_by": "Hannah Brooks"})])
inv_well = add_invoice(bc, "wellness", c_wellness, ev_well, q_well, "full", q_well["total"], -12, -2, "overdue")

# 12. Summit client breakfast — completed -5, part paid
ev_bfast = event(bc, "summit-bfast", "Summit Client Appreciation Breakfast", c_summit, etype="Corporate",
                 days=-5, start="07:00", finish="10:00", venue="Hotel Realm ballroom", address="Barton, ACT",
                 guests=120, budget=1800, status="completed", assigned=S, staff=(S, T),
                 services=("Espresso cart", "Catering"), equipment=("Cart 1",), calendar=cal["cart1"])
q_bf = build_quote(bc, "summit-bfast", ev_bfast, c_summit, "Client breakfast coffee & pastries",
                   [("Coffee service", [cart_hire(3), barista(2, 3), cups(160)]),
                    ("Catering", [{"name": "Pastry & biscotti platter", "qty": 120, "unit": "guest",
                                   "price": 6.5}])],
                   status="accepted", issue_days=-25, expiry_days=5,
                   versions=[("accepted", 25 * DAY, {"by": S, "viewed": 24 * DAY, "responded": 24 * DAY - 300,
                                                     "accepted_by": "Andrew Kim"})])
add_invoice(bc, "summit-bfast", c_summit, ev_bfast, q_bf, "full", q_bf["total"], -5, 9, "part_paid",
            paid=Decimal("500"), paid_minutes_ago=2 * DAY)

# 13. Makers market — +33 days confirmed, deposit overdue
e = enquiry(bc, "makers", "Coffee stall at the spring makers market", cust=c_makers, etype="Market", days=33,
            guests=800, budget=2500, venue="Old Bus Depot Markets", source="email", status="won", assigned=S,
            received_ago=20 * DAY, last_contact_ago=10 * DAY,
            message="We'd like a coffee stall for the full market day.")
ev_makers = event(bc, "makers", "Spring Makers Market", c_makers, etype="Market", days=33, start="09:00",
                  finish="16:00", venue="Old Bus Depot Markets", address="Kingston, ACT", guests=800,
                  budget=2500, status="confirmed", assigned=S, staff=(J, T),
                  services=("Espresso cart",), equipment=("Cart 1", "Cart 2"), calendar=cal["cart1"],
                  next_action="Chase deposit (overdue)", next_due=AT(0, "15:00"))
link(bc, e, ev_makers)
q_mk = build_quote(bc, "makers", ev_makers, c_makers, "Market day coffee stall",
                   [("Coffee service", [cart_hire(7), barista(3, 7), cups(450)])],
                   status="accepted", issue_days=-15, expiry_days=15,
                   versions=[("accepted", 15 * DAY, {"by": S, "viewed": 14 * DAY, "responded": 13 * DAY,
                                                     "accepted_by": "Sophie Turner"})])
add_invoice(bc, "makers-dep", c_makers, ev_makers, q_mk, "deposit", q_mk["total"] * Decimal("0.3"), -13, -1, "overdue")

# 14. Bennett wedding — planning +95
e_ben = enquiry(bc, "bennett", "Wedding coffee — Emma Smith recommended you!", cust=c_bennett,
                etype="Wedding", days=95, guests=130, budget=4000, venue="Pialligo Estate", source="referral",
                status="won", assigned=J, received_ago=10 * DAY, last_contact_ago=2 * DAY,
                message="Emma Smith said you were amazing. We're getting married in the new year — ~130 guests.",
                classification="event_enquiry", confidence=0.94)
ev_ben = event(bc, "bennett", "Bennett Wedding", c_bennett, etype="Wedding", days=95, start="15:00",
               finish="20:00", venue="Pialligo Estate", address="Pialligo, ACT", guests=130, budget=4000,
               status="planning", assigned=J, staff=(J,), services=("Espresso cart",),
               next_action="Book site inspection", next_due=AT(4, "10:00"))
link(bc, e_ben, ev_ben)

# ---- open enquiries (not yet events) ---------------------------------------
e_oc = enquiry(bc, "oconnor", "Engagement party — coffee cart", contact_name="Daniel O'Connor",
               contact_email="d.oconnor@example.com", contact_phone="0488 555 204", etype="Engagement", days=41,
               guests=70, budget=1500, venue="Private residence, Hackett", source="website", status="new",
               assigned=None, received_ago=2 * H,
               message="Website form: Engagement party on a Saturday afternoon, around 70 guests. Looking for a "
                       "coffee cart 2–5pm. Budget about $1,500.", classification="event_enquiry",
               confidence=0.98, next_action="Reply & check availability", next_due=AHEAD(2 * H))
e_nina = enquiry(bc, "nina", "Weekly coffee cart — Barton offices", contact_name="Nina Patel",
                 contact_email="nina.patel@example.com", company="Barton Consulting", etype="Corporate",
                 days=14, guests=90, budget=None, venue="Barton Consulting", source="website", status="new",
                 assigned=None, received_ago=30, message="Website form: Interested in a recurring Friday coffee "
                 "cart for our staff (~90). Can you send pricing?", classification="event_enquiry",
                 confidence=0.95, next_action="Reply with recurring pricing", next_due=AHEAD(4 * H))
e_mia = enquiry(bc, "mia", "Baby shower coffee & hot chocolate", contact_name="Mia Thompson",
                contact_email="mia.t@example.com", etype="Private party", days=26, guests=35, budget=800,
                venue="Private residence", source="instagram", status="new", assigned=None, received_ago=5 * H,
                message="Instagram DM: Do you do small events? Baby shower for 35, would love hot chocolate too.",
                next_action="Reply to Instagram DM", next_due=AHEAD(1 * H))
e_parkes = enquiry(bc, "parkes", "Conference barista service — 400 delegates", cust=c_parkes,
                   etype="Conference", days=50, guests=400, budget=9000, venue="National Convention Centre",
                   source="email", status="quote_required", assigned=S, received_ago=26 * H,
                   last_contact_ago=20 * H, message="We're running a 2-day tech conference and need barista "
                   "service at morning tea and lunch both days. Two carts?", classification="event_enquiry",
                   confidence=0.92, next_action="Prepare quote", next_due=AHEAD(20 * H))
e_ethan = enquiry(bc, "ethan", "Quick question about Saturday", contact_name="Ethan Wright",
                  contact_email="ethan.wright@example.com", etype=None, days=None, guests=None, budget=None,
                  venue=None, source="email", status="needs_review", assigned=None, received_ago=70,
                  message="Hey, are you guys around Saturday? Might need something for the team, not sure yet.",
                  classification="needs_review", confidence=0.42, next_action="Review — new event or general?",
                  next_due=AHEAD(3 * H))
e_redgum = enquiry(bc, "redgum", "Film shoot — crew coffee for 3 days", cust=c_harbour, etype="Film shoot",
                   days=21, guests=45, budget=2500, venue="Various locations, Canberra", source="phone",
                   status="contacted", assigned=T, received_ago=3 * DAY, last_contact_ago=3 * DAY - 120,
                   message="Phone call: 3-day shoot, crew of ~45, early starts (6am). Chloe to email call sheet.",
                   next_action="Waiting on call sheet", next_due=AT(1, "10:00"))
e_rotary = enquiry(bc, "rotary", "Rotary charity breakfast", cust=c_rotary, etype="Community", days=30,
                   guests=150, budget=1600, venue="Kingston Rotary Hall", source="referral", status="qualified",
                   assigned=J, received_ago=4 * DAY, last_contact_ago=1 * DAY,
                   message="Charity breakfast for 150 — coffee from 7am. Referred by Brindabella Running Club.",
                   next_action="Convert to event & quote", next_due=AT(0, "17:00"))
e_lucy = enquiry(bc, "lucy", "21st birthday coffee cart", cust=c_lucy, etype="Birthday", days=-10, guests=50,
                 budget=400, venue="Private residence", source="website", status="lost", assigned=T,
                 received_ago=35 * DAY, last_contact_ago=30 * DAY, message="Coffee cart for 21st, budget $400.",
                 lost_reason="Budget too low for minimum booking")
e_old = enquiry(bc, "old", "Christmas party enquiry (last year)", contact_name="Frank Li",
                contact_email="frank.li@example.com", etype="Corporate", days=None, guests=80, budget=None,
                venue=None, source="email", status="archived", assigned=S, received_ago=300 * DAY,
                message="Christmas party coffee — no response after two follow-ups.")

# ---- email threads ---------------------------------------------------------
thread(bc, "smith", "Coffee cart for our wedding", "existing_event", "needs_reply", [
    msg("inbound", "emma.smith@example.com", "Emma Smith", [BC_EMAIL], 120 * DAY,
        "Hi! We're getting married and would love a coffee cart for the post-ceremony drinks. Around 80 guests. "
        "Do you do oat milk and chai?"),
    msg("outbound", BC_EMAIL, "Jess Harper", ["emma.smith@example.com"], 119 * DAY,
        "Hi Emma, congratulations! We'd love to be part of it. Yes to oat milk and chai. I'll put a quote together.",
        by=J),
    msg("outbound", BC_EMAIL, "Jess Harper", ["emma.smith@example.com"], 94 * DAY,
        "Hi Emma, here's the updated quote with two baristas for 100 guests. You can view and accept it online.",
        by=J),
    msg("inbound", "emma.smith@example.com", "Emma Smith", [BC_EMAIL], 92 * DAY,
        "Perfect — accepted! Deposit paid today."),
    msg("inbound", "emma.smith@example.com", "Emma Smith", [BC_EMAIL], 1 * DAY,
        "Hi Jess! RSVPs are in — we're at 100 confirmed. Could the cart be near the marquee entrance? Also, is "
        "there anything you need from our venue coordinator?", read=False),
], customer=c_smith, event=ev_smith)

thread(bc, "molonglo", f"Quote Q-{q_mol['number']} — Display village launch", "quote_discussion", "needs_reply", [
    msg("outbound", BC_EMAIL, "Sarah Mitchell", ["marcus.chen@example.com"], 3 * DAY,
        "Hi Marcus, please find our quote for the two-day launch attached. Happy to adjust hours.", by=S),
    msg("inbound", "marcus.chen@example.com", "Marcus Chen", [BC_EMAIL], 6 * H,
        "Thanks Sarah. Two questions: can we add branded cups, and could Sunday finish at 2pm instead? If so "
        "I think we're good to approve.", read=False),
], customer=c_molonglo, event=ev_mol, enquiry=e_mol)

thread(bc, "sharma", "Your quote from Bean Culture", "quote_discussion", "awaiting_customer", [
    msg("inbound", "priya.sharma@example.com", "Priya Sharma", [BC_EMAIL], 8 * DAY,
        "Hi, I'm planning my 40th at home (garden party, ~60 people). Could you do coffee from 2pm–5pm?"),
    msg("outbound", BC_EMAIL, "Jess Harper", ["priya.sharma@example.com"], 4 * DAY,
        "Hi Priya, happy (early) birthday! Here's your quote for the garden party. Let me know if you have any "
        "questions.", by=J),
], customer=c_sharma, event=ev_sh, enquiry=e_sh)

thread(bc, "oconnor", "New website enquiry: Engagement party", "event_enquiry", "needs_reply", [
    msg("inbound", "forms@beanculture.com.au", "Bean Culture Website", [BC_EMAIL], 2 * H,
        "Name: Daniel O'Connor\nEmail: d.oconnor@example.com\nPhone: 0488 555 204\nEvent: Engagement party\n"
        "Guests: 70\nBudget: $1,500\nMessage: Saturday afternoon, looking for a coffee cart 2–5pm.", read=False),
], enquiry=e_oc, confidence=0.98)

thread(bc, "nina", "New website enquiry: Corporate coffee cart", "event_enquiry", "needs_reply", [
    msg("inbound", "forms@beanculture.com.au", "Bean Culture Website", [BC_EMAIL], 30,
        "Name: Nina Patel\nCompany: Barton Consulting\nEmail: nina.patel@example.com\nMessage: Interested in a "
        "recurring Friday coffee cart for our staff (~90). Can you send pricing?", read=False),
], enquiry=e_nina, confidence=0.95)

thread(bc, "parkes", "Barista service for tech conference", "event_enquiry", "awaiting_customer", [
    msg("inbound", "rachel.adams@example.com", "Rachel Adams", [BC_EMAIL], 26 * H,
        "Hi, we're running a 2-day tech conference (400 delegates) at the NCC and need barista service at "
        "morning tea and lunch both days. Could you do two carts?"),
    msg("outbound", BC_EMAIL, "Sarah Mitchell", ["rachel.adams@example.com"], 20 * H,
        "Hi Rachel, yes — two carts is exactly what we'd recommend for 400. I'll have a quote to you tomorrow.",
        by=S),
], customer=c_parkes, enquiry=e_parkes)

thread(bc, "ethan", "Quick question about Saturday", "needs_review", "needs_reply", [
    msg("inbound", "ethan.wright@example.com", "Ethan Wright", [BC_EMAIL], 70,
        "Hey, are you guys around Saturday? Might need something for the team, not sure yet.", read=False),
], enquiry=e_ethan, confidence=0.42)

thread(bc, "harper", "Tomorrow — access details", "existing_event", "closed", [
    msg("inbound", "olivia@example.net", "Olivia Lane", [BC_EMAIL], 1 * DAY + 3 * H,
        "Hi Jess, rear lane gate code is 4471. We'll have someone there from 6:45."),
    msg("outbound", BC_EMAIL, "Jess Harper", ["olivia@example.net"], 1 * DAY,
        "Thanks Olivia — Tom will be there at 6:45 with the cart. See you tomorrow!", by=J),
], customer=c_harper, event=ev_harper)

thread(bc, "wellness", f"Invoice {inv_well['number']} is overdue", "existing_event", "awaiting_customer", [
    msg("outbound", BC_EMAIL, "Tom Nguyen", ["hannah@example.net"], 1 * DAY,
        f"Hi Hannah, a friendly reminder that {inv_well['number']} was due two days ago. Thanks again for having us!", by=T),
], customer=c_wellness, event=ev_well)

thread(bc, "runclub", "Parking for the cart", "existing_event", "open", [
    msg("inbound", "kate.ellis@example.org", "Kate Ellis", [BC_EMAIL], 2 * DAY,
        "We've reserved a spot beside the finish chute. Can you arrive by 6am?"),
    msg("outbound", BC_EMAIL, "Jess Harper", ["kate.ellis@example.org"], 2 * DAY - 40,
        "Absolutely, we'll be there at 5:45 to set up. Bringing the generator.", by=J),
], customer=c_runclub, event=ev_run)

thread(bc, "supplier", "October milk delivery schedule", "supplier", "open", [
    msg("inbound", "orders@highland-dairy.example", "Highland Dairy Co", [BC_EMAIL], 3 * DAY,
        "Hi team, October deliveries move to Tuesdays and Fridays."),
], confidence=0.88)

thread(bc, "spam", "Boost your Google rankings today!!!", "spam", "closed", [
    msg("inbound", "growth@seo-blast.example", "SEO Blast", [BC_EMAIL], 5 * H,
        "We can get you to #1 on Google in 7 days guaranteed..."),
], confidence=0.99)

thread(bc, "bennett", "Wedding coffee — Emma Smith recommended you!", "event_enquiry", "awaiting_customer", [
    msg("inbound", "grace.bennett@example.com", "Grace Bennett", [BC_EMAIL], 10 * DAY,
        "Emma Smith said you were amazing. We're getting married in the new year — ~130 guests at Pialligo."),
    msg("outbound", BC_EMAIL, "Jess Harper", ["grace.bennett@example.com"], 2 * DAY,
        "Hi Grace! We'd love to. Could we book a quick site visit at Pialligo next week?", by=J),
], customer=c_bennett, event=ev_ben, enquiry=e_ben)

thread(bc, "rotary", "Charity breakfast — coffee", "event_enquiry", "open", [
    msg("inbound", "peter.hughes@example.org", "Peter Hughes", [BC_EMAIL], 4 * DAY,
        "Kate from the running club said you're great. Charity breakfast for 150, coffee from 7am?"),
    msg("outbound", BC_EMAIL, "Jess Harper", ["peter.hughes@example.org"], 1 * DAY,
        "Hi Peter, we're available that morning. I'll send through a quote shortly.", by=J),
], customer=c_rotary, enquiry=e_rotary)

# ---- tasks -----------------------------------------------------------------
def task(o, title, *, due, assigned, priority="normal", status="open", event=None, enquiry=None, cust=None,
         desc=None):
    o.tasks.append(dict(organisation_id=o.id, title=title, description=desc, status=Raw(f"'{status}'"),
                        priority=Raw(f"'{priority}'"), due_at=due, assigned_to=assigned,
                        customer_id=cust["id"] if cust else None, event_id=event["id"] if event else None,
                        enquiry_id=enquiry["id"] if enquiry else None,
                        completed_at=AGO(60) if status == "done" else None, created_by=assigned))


task(bc, "Follow up Priya's quote", due=AT(-1, "10:00"), assigned=J, priority="high", event=ev_sh, cust=c_sharma)
task(bc, f"Chase overdue invoice {inv_well['number']}", due=AT(0, "11:00"), assigned=T, priority="high", event=ev_well,
     cust=c_wellness)
task(bc, "Chase Makers Market deposit", due=AT(0, "15:00"), assigned=S, priority="high", event=ev_makers,
     cust=c_makers)
task(bc, "Reply to Marcus — branded cups & Sunday hours", due=AHEAD(3 * H), assigned=S, priority="urgent",
     event=ev_mol, cust=c_molonglo)
task(bc, "Send final details form to Emma", due=AT(2, "09:00"), assigned=J, event=ev_smith, cust=c_smith)
task(bc, "Finish End of Year quote", due=AT(1, "12:00"), assigned=S, event=ev_eoy, cust=c_captech)
task(bc, "Fuel generator & check gazebo", due=AT(1, "16:00"), assigned=T, event=ev_run, cust=c_runclub)
task(bc, "Prepare conference quote (2 carts)", due=AHEAD(20 * H), assigned=S, enquiry=e_parkes, cust=c_parkes)
task(bc, "Book Pialligo site inspection", due=AT(4, "10:00"), assigned=J, event=ev_ben, cust=c_bennett)
task(bc, "Load Cart 1 for Harper & Lane", due=AT(0, "06:15"), assigned=T, status="done", event=ev_harper,
     cust=c_harper)
task(bc, "Order branded cups sample", due=AT(6, "12:00"), assigned=T, priority="low", event=ev_mol,
     cust=c_molonglo)

# ---- documents -------------------------------------------------------------
for name, ev_, cu, vis, req in [
    ("Lanyon Homestead site map.pdf", ev_smith, c_smith, "internal", False),
    ("Wedding run sheet.pdf", ev_smith, c_smith, "customer", False),
    ("Public liability certificate 2026.pdf", ev_run, c_runclub, "customer", False),
    ("Venue access & parking.pdf", ev_harper, c_harper, "internal", False),
    ("Final details form", ev_smith, c_smith, "customer", True),
]:
    bc.documents.append(dict(organisation_id=BC, name=name, storage_path=None,
                             mime_type="application/pdf" if name.endswith(".pdf") else None,
                             size_bytes=184_320 if name.endswith(".pdf") else None, customer_id=cu["id"],
                             event_id=ev_["id"], visibility=vis, requested_from_customer=req, uploaded_by=J))

# ---- activity timeline -----------------------------------------------------
names = {S: "Sarah Mitchell", J: "Jess Harper", T: "Tom Nguyen"}


def timeline(o, ev, cust, enq, quote, actor, *, received, replied=None, site=None, quote_created=None,
             quote_sent=None, viewed=None, accepted=None, deposit_inv=None, deposit_paid=None, confirmed=None,
             details=None, completed=None, final_paid=None, accepted_by=None):
    base = dict(event_id=ev["id"], customer_id=cust["id"], enquiry_id=enq["id"] if enq else None)
    if enq:
        o.log(AGO(received), "enquiry.received", "enquiry", enq["id"], f"Enquiry received — {enq['title']}",
              actor_type="system", actor_label=enq.get("source", "Website"), **base)
    if replied:
        o.log(AGO(replied), "email.replied", "email", None, f"{names.get(actor, 'Staff')} replied by email",
              actor=actor, **base)
    if site:
        o.log(AGO(site), "event.site_inspection", "event", ev["id"], "Site inspection completed", actor=actor, **base)
    o.log(AGO((quote_created or received) - 30), "event.created", "event", ev["id"],
          f"{names.get(actor, 'Staff')} created event EV-{ev['number']}", actor=actor, **base)
    if quote and quote_created:
        o.log(AGO(quote_created), "quote.created", "quote", quote["id"],
              f"{names.get(actor, 'Staff')} created Quote Q-{quote['number']}", actor=actor, **base)
    if quote and quote_sent:
        o.log(AGO(quote_sent), "quote.sent", "quote", quote["id"], f"Quote Q-{quote['number']} sent to customer",
              actor=actor, **base)
    if quote and viewed:
        o.log(AGO(viewed), "quote.viewed", "quote", quote["id"], "Customer viewed quote", actor_type="customer",
              actor_label=cust["contact"], **base)
    if quote and accepted:
        o.log(AGO(accepted), "quote.accepted", "quote", quote["id"],
              f"Customer accepted quote Q-{quote['number']}", actor_type="customer",
              actor_label=accepted_by or cust["contact"], metadata={"ip": "203.0.113.24"}, **base)
    if deposit_inv:
        o.log(AGO(deposit_inv[1]), "invoice.created", "invoice", deposit_inv[0]["id"],
              f"Deposit invoice {deposit_inv[0]['number']} generated", actor_type="system",
              actor_label="Automation", **base)
    if deposit_paid:
        o.log(AGO(deposit_paid), "payment.received", "invoice", None, "Deposit paid", actor_type="system",
              actor_label="Payments", **base)
    if confirmed:
        o.log(AGO(confirmed), "event.status_changed", "event", ev["id"], "Event confirmed", actor_type="system",
              actor_label="Automation", changes={"status": ["awaiting_approval", "confirmed"]}, **base)
    if details:
        o.log(AGO(details), "event.details_requested", "event", ev["id"], "Final details requested",
              actor=actor, **base)
    if completed:
        o.log(AGO(completed), "event.status_changed", "event", ev["id"], "Event completed", actor=actor,
              changes={"status": ["confirmed", "completed"]}, **base)
    if final_paid:
        o.log(AGO(final_paid), "payment.received", "invoice", None, "Final invoice paid", actor_type="system",
              actor_label="Payments", **base)


e_by_key = {r["id"]: r for r in bc.enquiries}


def enq_of(ev):
    r = next(x for x in bc.events if x["id"] == ev["id"])
    row = e_by_key.get(r.get("enquiry_id"))
    if not row:
        return None
    return dict(id=row["id"], title=row["title"], source=row["source"].sql.strip("'").capitalize())


timeline(bc, ev_smith, c_smith, enq_of(ev_smith), q_smith, J, received=120 * DAY, replied=119 * DAY,
         site=110 * DAY, quote_created=101 * DAY, quote_sent=100 * DAY, viewed=93 * DAY, accepted=92 * DAY,
         deposit_inv=(inv_smith_dep, 92 * DAY - 5), deposit_paid=88 * DAY, confirmed=88 * DAY - 1)
bc.log(AGO(40 * DAY), "event.updated", "event", ev_smith["id"], "Jess Harper changed guest count 80 → 100",
       actor=J, event_id=ev_smith["id"], customer_id=c_smith["id"], changes={"guest_count": [80, 100]})
bc.log(AGO(2 * DAY), "invoice.created", "invoice", inv_smith_fin["id"], f"Final invoice {inv_smith_fin['number']} created",
       actor=J, event_id=ev_smith["id"], customer_id=c_smith["id"])
bc.log(AGO(1 * DAY), "email.received", "email", None, "Emma Smith replied — final guest numbers",
       actor_type="customer", actor_label="Emma Smith", event_id=ev_smith["id"], customer_id=c_smith["id"])

timeline(bc, ev_offsite, c_captech, enq_of(ev_offsite), q_off, S, received=70 * DAY, replied=69 * DAY,
         quote_created=66 * DAY + 60, quote_sent=66 * DAY, viewed=65 * DAY, accepted=64 * DAY,
         confirmed=64 * DAY - 1, completed=39 * DAY, final_paid=30 * DAY)
timeline(bc, ev_eoy, c_captech, enq_of(ev_eoy), None, S, received=9 * DAY, replied=6 * DAY)
bc.log(AGO(5 * 60), "quote.draft_updated", "quote", None, "Sarah Mitchell edited draft quote (not yet sent)",
       actor=S, event_id=ev_eoy["id"], customer_id=c_captech["id"])
timeline(bc, ev_harper, c_harper, enq_of(ev_harper), q_harper, J, received=35 * DAY, replied=34 * DAY,
         quote_created=30 * DAY + 60, quote_sent=30 * DAY, viewed=29 * DAY, accepted=28 * DAY,
         confirmed=28 * DAY - 1, details=10 * DAY)
timeline(bc, ev_board, c_summit, None, q_board, S, received=13 * DAY, quote_created=12 * DAY + 30,
         quote_sent=12 * DAY, viewed=12 * DAY - 90, accepted=11 * DAY, confirmed=11 * DAY - 1)
timeline(bc, ev_run, c_runclub, enq_of(ev_run), q_run, J, received=40 * DAY, replied=39 * DAY,
         quote_created=36 * DAY + 30, quote_sent=36 * DAY, viewed=35 * DAY, accepted=35 * DAY - 200,
         confirmed=35 * DAY - 201, final_paid=18 * DAY)
timeline(bc, ev_school, c_school, enq_of(ev_school), q_school, T, received=50 * DAY, replied=49 * DAY,
         quote_created=45 * DAY + 60, quote_sent=45 * DAY, viewed=44 * DAY, accepted=42 * DAY,
         deposit_paid=6 * DAY, confirmed=42 * DAY - 1)
timeline(bc, ev_mol, c_molonglo, enq_of(ev_mol), q_mol, S, received=11 * DAY, replied=10 * DAY,
         quote_created=3 * DAY + 90, quote_sent=3 * DAY, viewed=20 * H)
bc.log(AGO(6 * H), "email.received", "email", None, "Marcus Chen replied with questions about the quote",
       actor_type="customer", actor_label="Marcus Chen", event_id=ev_mol["id"], customer_id=c_molonglo["id"],
       enquiry_id=e_mol["id"])
timeline(bc, ev_sh, c_sharma, enq_of(ev_sh), q_sh, J, received=8 * DAY, replied=7 * DAY,
         quote_created=4 * DAY + 60, quote_sent=4 * DAY)
bc.log(AGO(10 * H), "automation.follow_up_flagged", "quote", q_sh["id"],
       "Follow-up flagged — no reply to quote after 3 days", actor_type="system", actor_label="Automation",
       event_id=ev_sh["id"], customer_id=c_sharma["id"])
timeline(bc, ev_well, c_wellness, enq_of(ev_well), q_well, T, received=45 * DAY, replied=44 * DAY,
         quote_created=40 * DAY + 60, quote_sent=40 * DAY, viewed=39 * DAY, accepted=38 * DAY,
         confirmed=38 * DAY - 1, completed=12 * DAY - 300)
bc.log(AGO(2 * DAY), "invoice.overdue", "invoice", inv_well["id"], f"Invoice {inv_well['number']} is overdue",
       actor_type="system", actor_label="Automation", event_id=ev_well["id"], customer_id=c_wellness["id"])
timeline(bc, ev_bfast, c_summit, None, q_bf, S, received=26 * DAY, quote_created=25 * DAY + 60,
         quote_sent=25 * DAY, viewed=24 * DAY, accepted=24 * DAY - 300, confirmed=24 * DAY - 301,
         completed=5 * DAY - 400)
bc.log(AGO(2 * DAY), "payment.received", "invoice", None, "Part payment received — $500.00",
       actor_type="system", actor_label="Payments", event_id=ev_bfast["id"], customer_id=c_summit["id"])
timeline(bc, ev_makers, c_makers, enq_of(ev_makers), q_mk, S, received=20 * DAY, replied=19 * DAY,
         quote_created=15 * DAY + 60, quote_sent=15 * DAY, viewed=14 * DAY, accepted=13 * DAY,
         confirmed=13 * DAY - 1)
timeline(bc, ev_ben, c_bennett, enq_of(ev_ben), None, J, received=10 * DAY, replied=2 * DAY)
bc.log(AGO(9 * DAY + 100), "event.status_changed", "event", ev_kingston["id"], "Event cancelled — permit not approved",
       actor=S, event_id=ev_kingston["id"], customer_id=c_kingston["id"], changes={"status": ["confirmed", "cancelled"]})

for en, label in [(e_oc, "Website"), (e_nina, "Website"), (e_mia, "Instagram"), (e_parkes, "Email"),
                  (e_ethan, "Email"), (e_redgum, "Phone"), (e_rotary, "Referral")]:
    bc.log(AGO(en["received_ago"]), "enquiry.received", "enquiry", en["id"], f"Enquiry received — {en['title']}",
           actor_type="system", actor_label=label, enquiry_id=en["id"],
           customer_id=en["customer"]["id"] if en["customer"] else None)
bc.log(AGO(20 * H), "email.replied", "email", None, "Sarah Mitchell replied by email", actor=S,
       enquiry_id=e_parkes["id"], customer_id=c_parkes["id"])
bc.log(AGO(3 * DAY - 120), "enquiry.status_changed", "enquiry", e_redgum["id"], "Tom Nguyen marked enquiry Contacted",
       actor=T, enquiry_id=e_redgum["id"], customer_id=c_harbour["id"], changes={"status": ["new", "contacted"]})
bc.log(AGO(1 * DAY), "enquiry.status_changed", "enquiry", e_rotary["id"], "Jess Harper marked enquiry Qualified",
       actor=J, enquiry_id=e_rotary["id"], customer_id=c_rotary["id"], changes={"status": ["contacted", "qualified"]})
bc.log(AGO(30 * DAY), "enquiry.status_changed", "enquiry", e_lucy["id"], "Tom Nguyen marked enquiry Lost",
       actor=T, enquiry_id=e_lucy["id"], customer_id=c_lucy["id"], changes={"status": ["contacted", "lost"]})

# ---- notifications ---------------------------------------------------------
for ntype, title, body, link_, ago, read in [
    ("enquiry.new", "New enquiry from Nina Patel", "Weekly coffee cart — Barton offices", f"/enquiries/{e_nina['id']}", 30, False),
    ("email.needs_review", "Email needs review", "Ethan Wright — 'Quick question about Saturday'", f"/enquiries/{e_ethan['id']}", 70, False),
    ("enquiry.new", "New enquiry from Daniel O'Connor", "Engagement party — coffee cart", f"/enquiries/{e_oc['id']}", 2 * H, False),
    ("customer.replied", "Marcus Chen replied", f"Questions about Quote Q-{q_mol['number']}", f"/events/{ev_mol['id']}?tab=communication", 6 * H, False),
    ("quote.viewed", f"Quote Q-{q_mol['number']} viewed", "Molonglo Property Group viewed the quote", f"/events/{ev_mol['id']}?tab=quote", 20 * H, False),
    ("customer.replied", "Emma Smith replied", "Final guest numbers for the wedding", f"/events/{ev_smith['id']}?tab=communication", 1 * DAY, True),
    ("invoice.overdue", f"Invoice {inv_well['number']} overdue", "Lakeside Wellness Studio — 2 days overdue", f"/events/{ev_well['id']}?tab=invoice", 2 * DAY, True),
    ("payment.received", "Payment received", "$500.00 from Summit Financial Advisers", f"/events/{ev_bfast['id']}?tab=payments", 2 * DAY, True),
    ("task.overdue", "Task overdue", "Follow up Priya's quote", f"/events/{ev_sh['id']}?tab=tasks", 10 * H, False),
]:
    bc.notifications.append(dict(organisation_id=BC, user_id=None, type=ntype, title=title, body=body, link=link_,
                                 read_at=AGO(ago - 10) if read else None, created_at=AGO(ago)))

# ===========================================================================
# COPPER & TONIC (second tenant — proves isolation)
# ===========================================================================
ct = Org(CT, "ct")
L = U["liam"]
CT_EMAIL = "hello@copperandtonic.demo"
ccal = {"main": ct.k("cal", "main"), "trailer": ct.k("cal", "trailer")}
insert("calendar_connections", [
    dict(id=ccal["main"], organisation_id=CT, name="Main Events", colour="#B4632B", is_default=True),
    dict(id=ccal["trailer"], organisation_id=CT, name="Bar Trailer", colour="#0E9F6E", is_default=False),
])


def bar_lines(guests, hours):
    return [("Bar service", [
        {"name": "Mobile bar trailer hire", "desc": "Vintage caravan bar, fridges & setup", "qty": 1, "unit": "event",
         "price": 900.0},
        {"name": "Bartender", "desc": f"2 bartenders × {hours} hrs", "qty": 2 * hours, "unit": "hour", "price": 65.0},
        {"name": "Signature cocktail package", "desc": "3 signature cocktails, per guest", "qty": guests,
         "unit": "guest", "price": 38.0, "package": True}])]


ct_c1 = customer(ct, "wilson", "Hayley Wilson", email="hayley.wilson@example.com", phone="0413 555 772",
                 since=-90, source="instagram", tags=("wedding",))
ct_c2 = customer(ct, "govlaw", "Burley Legal", kind="company", company="Burley Legal", contact="Tim Park",
                 email="tim.park@example.com", phone="02 6100 4411", since=-200, source="referral",
                 tags=("corporate",))
ct_c3 = customer(ct, "garcia", "Luis Garcia", email="luis.garcia@example.com", since=-12, source="website")
ct_c4 = customer(ct, "smithct", "Jordan Smith", email="jordan.smith@example.com", since=-6, source="website",
                 notes="Not related to Bean Culture's Smith wedding — separate tenant, separate data.")

e1 = enquiry(ct, "wilson", "Cocktail bar for our wedding", cust=ct_c1, etype="Wedding", days=40, guests=90,
             budget=6000, venue="Mount Majura Vineyard", source="instagram", status="won", assigned=L,
             received_ago=60 * DAY, last_contact_ago=3 * DAY, message="Love your caravan bar! Wedding for 90.")
cev1 = event(ct, "wilson", "Wilson Wedding Cocktail Bar", ct_c1, etype="Wedding", days=40, start="16:00",
             finish="22:00", venue="Mount Majura Vineyard", address="Majura, ACT", guests=90, budget=6000,
             status="confirmed", assigned=L, staff=(L,), services=("Cocktail bar",), equipment=("Bar trailer",),
             calendar=ccal["trailer"], next_action="Confirm cocktail menu", next_due=AT(7, "10:00"))
link(ct, e1, cev1)
cq1 = build_quote(ct, "wilson", cev1, ct_c1, "Wedding cocktail bar", bar_lines(90, 6), status="accepted",
                  issue_days=-50, expiry_days=-20,
                  versions=[("accepted", 50 * DAY, {"by": L, "viewed": 49 * DAY, "responded": 47 * DAY,
                                                    "accepted_by": "Hayley Wilson"})])
add_invoice(ct, "wilson-dep", ct_c1, cev1, cq1, "deposit", cq1["total"] * Decimal("0.3"), -47, -40, "paid",
            paid=cq1["total"] * Decimal("0.3"), paid_minutes_ago=41 * DAY)

e2 = enquiry(ct, "govlaw", "Friday drinks — end of financial year", cust=ct_c2, etype="Corporate", days=16,
             guests=60, budget=3500, venue="Burley Legal rooftop", source="referral", status="quote_sent",
             assigned=L, received_ago=6 * DAY, last_contact_ago=2 * DAY, message="Rooftop drinks for 60 staff.",
             next_action="Follow up quote", next_due=AT(1, "10:00"))
cev2 = event(ct, "govlaw", "Burley Legal Rooftop Drinks", ct_c2, etype="Corporate", days=16, start="17:00",
             finish="21:00", venue="Burley Legal rooftop", address="Canberra City, ACT", guests=60, budget=3500,
             status="quoted", assigned=L, services=("Cocktail bar",), next_action="Follow up quote",
             next_due=AT(1, "10:00"))
link(ct, e2, cev2)
cq2 = build_quote(ct, "govlaw", cev2, ct_c2, "Rooftop cocktail bar", bar_lines(60, 4), status="sent",
                  issue_days=-2, expiry_days=12, versions=[("sent", 2 * DAY, {"by": L})])

e3 = enquiry(ct, "garcia", "30th birthday — espresso martini bar", cust=ct_c3, etype="Birthday", days=27,
             guests=40, budget=2000, venue="Private residence, Googong", source="website", status="new",
             assigned=None, received_ago=3 * H, message="Website form: 30th, espresso martinis, 40 guests.",
             classification="event_enquiry", confidence=0.97, next_action="Reply & check availability",
             next_due=AHEAD(3 * H))
e4 = enquiry(ct, "smithct", "Smith wedding — bar quote", cust=ct_c4, etype="Wedding", days=120, guests=150,
             budget=8000, venue="Gibraltar Hall", source="website", status="contacted", assigned=L,
             received_ago=6 * DAY, last_contact_ago=5 * DAY, message="Bar for a 150-guest wedding.")

cev3 = event(ct, "past", "Burley Legal Christmas Party", ct_c2, etype="Corporate", days=-30, start="18:00",
             finish="23:00", venue="Burley Legal", address="Canberra City, ACT", guests=80, budget=5000,
             status="completed", assigned=L, services=("Cocktail bar",), calendar=ccal["trailer"])
cq3 = build_quote(ct, "past", cev3, ct_c2, "Christmas party bar", bar_lines(80, 5), status="accepted",
                  issue_days=-60, expiry_days=-30,
                  versions=[("accepted", 60 * DAY, {"by": L, "viewed": 59 * DAY, "responded": 58 * DAY,
                                                    "accepted_by": "Tim Park"})])
add_invoice(ct, "past", ct_c2, cev3, cq3, "full", cq3["total"], -30, -16, "paid", paid=cq3["total"],
            paid_minutes_ago=20 * DAY)

thread(ct, "garcia", "New website enquiry: 30th birthday", "event_enquiry", "needs_reply", [
    msg("inbound", "forms@copperandtonic.demo", "Copper & Tonic Website", [CT_EMAIL], 3 * H,
        "Name: Luis Garcia\nEvent: 30th birthday\nGuests: 40\nMessage: Espresso martini bar please!", read=False)],
       enquiry=e3)
thread(ct, "govlaw", "Rooftop drinks quote", "quote_discussion", "awaiting_customer", [
    msg("outbound", CT_EMAIL, "Liam O'Brien", ["tim.park@example.com"], 2 * DAY,
        "Hi Tim, quote attached for the rooftop drinks.", by=L)], customer=ct_c2, event=cev2, enquiry=e2)

task(ct, "Follow up Burley Legal quote", due=AT(1, "10:00"), assigned=L, priority="high", event=cev2, cust=ct_c2)
task(ct, "Reply to Luis Garcia", due=AHEAD(3 * H), assigned=L, enquiry=e3, cust=ct_c3)

ct.log(AGO(3 * H), "enquiry.received", "enquiry", e3["id"], "Enquiry received — 30th birthday — espresso martini bar",
       actor_type="system", actor_label="Website", enquiry_id=e3["id"], customer_id=ct_c3["id"])
ct.log(AGO(2 * DAY), "quote.sent", "quote", cq2["id"], f"Quote Q-{cq2['number']} sent to customer", actor=L,
       event_id=cev2["id"], customer_id=ct_c2["id"])
ct.log(AGO(47 * DAY), "quote.accepted", "quote", cq1["id"], f"Customer accepted quote Q-{cq1['number']}",
       actor_type="customer", actor_label="Hayley Wilson", event_id=cev1["id"], customer_id=ct_c1["id"])
ct.notifications.append(dict(organisation_id=CT, user_id=None, type="enquiry.new", title="New enquiry from Luis Garcia",
                             body="30th birthday — espresso martini bar", link=f"/enquiries/{e3['id']}", read_at=None,
                             created_at=AGO(3 * H)))

# ===========================================================================
# Emit rows in dependency order
# ===========================================================================
for o in (bc, ct):
    insert("customers", o.customers)
    insert("contacts", o.contacts)
    ev_rows = []
    for r in o.events:
        r = {k: v for k, v in r.items() if not k.startswith("_")}
        r["enquiry_id"] = None  # set after enquiries exist (circular FK)
        ev_rows.append(r)
    insert("events", ev_rows)
    insert("event_contacts", o.event_contacts)
    insert("enquiries", o.enquiries)
    for r in o.events:
        if r.get("enquiry_id"):
            out.append(f"update public.events set enquiry_id = {q(r['enquiry_id'])} where id = {q(r['id'])};\n")
    insert("quotes", [{k: v for k, v in r.items() if not k.startswith("_")} for r in o.quotes])
    insert("quote_sections", o.sections)
    insert("quote_items", o.items)
    insert("quote_versions", o.versions)
    # item inserts fire the "unpublished changes" trigger — restore the intended flags
    for r in o.quotes:
        out.append(f"update public.quotes set has_unpublished_changes = {q(r['has_unpublished_changes'])} where id = {q(r['id'])};\n")
    for r in o.quotes:
        if r["_current"]:
            out.append(f"update public.quotes set current_version_id = {q(r['_current'])} where id = {q(r['id'])};\n")
    insert("calendar_events", o.cal_events)
    insert("invoices", o.invoices)
    insert("payments", o.payments)
    insert("email_threads", o.threads)
    insert("email_messages", o.messages)
    insert("tasks", o.tasks)
    insert("documents", o.documents)
    insert("activity_logs", o.activity)
    insert("notifications", o.notifications)

    # counters continue after the seeded numbers
    out.append(
        f"insert into public.organisation_counters (organisation_id, key, value) values "
        f"({q(o.id)}, 'enquiries', {o.enq_n}), ({q(o.id)}, 'events', {o.ev_n}), "
        f"({q(o.id)}, 'quotes', {o.q_n}), ({q(o.id)}, 'invoice', {o.inv_n});\n")

    # integrations: nothing is connected yet (Phase 2/3)
    out.append(
        f"insert into public.integrations (organisation_id, provider) values "
        f"({q(o.id)}, 'gmail'), ({q(o.id)}, 'google_calendar'), ({q(o.id)}, 'xero');\n")

    out.append(
        f"""insert into public.automation_rules (organisation_id, name, trigger_type, actions, enabled) values
  ({q(o.id)}, 'Follow up unanswered quotes', 'quote.no_reply', '[{{"type":"flag_follow_up"}},{{"type":"create_task","params":{{"title":"Follow up quote"}}}}]', true),
  ({q(o.id)}, 'Quote accepted → confirm event', 'quote.accepted', '[{{"type":"set_event_status","params":{{"status":"confirmed"}}}},{{"type":"create_calendar_event"}},{{"type":"create_invoice","params":{{"kind":"deposit"}}}},{{"type":"notify_assigned"}}]', true),
  ({q(o.id)}, 'New enquiry → assign & notify', 'enquiry.created', '[{{"type":"assign_round_robin"}},{{"type":"notify_team"}}]', false),
  ({q(o.id)}, 'Invoice paid in Xero → update event', 'invoice.paid', '[{{"type":"mark_deposit_paid"}},{{"type":"update_portal"}}]', false);
""")

# Demo notes (notes table from migration 0006)
out.append("""insert into public.notes (organisation_id, body, event_id, customer_id, enquiry_id, created_by, created_at) values
  (demo.u('org:bean-culture'), 'Emma prefers email. Venue coordinator is Kylie — confirm power location on the lawn before the day.', demo.u('bc:event:smith'), demo.u('bc:cust:smith'), null, demo.u('user:jess'), now() - interval '20 days'),
  (demo.u('org:bean-culture'), 'Marcus is keen — likely to approve if we can do branded cups. Supplier needs 10 days lead time.', demo.u('bc:event:molonglo'), demo.u('bc:cust:molonglo'), null, demo.u('user:sarah'), now() - interval '5 hours'),
  (demo.u('org:bean-culture'), 'Two carts needed. Check Cart 2 availability — Summit might rebook that week.', null, null, demo.u('bc:enq:parkes'), demo.u('user:sarah'), now() - interval '19 hours');
""")

out.append("commit;\n")

Path(__file__).with_name("seed.sql").write_text("".join(out))
print("wrote seed.sql", sum(len(s) for s in out), "chars")
